### PR TITLE
Fix of issue 'Remove Eloquent calls from views #111'

### PR DESCRIPTION
**Pull request by marcmarina**
I have checked with how it was coded before, and it looks like the result is identical. Let me know if something's wrong :D

### CODE REVIEW

**Comment by laxsmi** [comment]
Hi @marcmarina and thanks for your interest in the project! I'm curious, are you a user of this application or just interested in contributing to the code?

I really appreciate your creating this PR. I reviewed your code and I think you're on the right track ; however I noticed it would break a small part of the existing code: the variable `$current_year` is updated with every iteration of the loop. If you extract it to the controller, it is not updated any longer and all "total" rows will show the same values. I believe you didn't notice it because the default seeded data only includes one year, but I updated and improved the database seeder to show more data :)

Screenshot from 2020-05-07 11-45-05

You're welcome to pull the latest commit on the master branch,  re-seed your database and review the difference between the master branch and your branch.

I hope it makes sense! It shouldn't be too hard to fix this, and I'll gladly accept your PR afterwards. The Reports modules is complex and could use various refactors ; this one will be a very nice first step :)

**Comment by marcmarina** [comment]
Hey there! I just came across the project and looked at the issues, to see if there was something quick I could help with. I will probably help more in the future, when I'm less busy. And no, I'm not a user, just wanted to contribute a bit.

Now I see that I missed the current year increment at the end of the loop, I've pulled the new seeder and I'm fixing it now. Thanks :D

**Comment by marcmarina** [comment]
Fixed it (I think), but it works differently on each page (internal/external). For **external**, I have used the already existing `$year_data` array to access the info, not using model attributes, but using the array's elements: `$year_data[$current_year_id]['year_name']`.

For **internal**, since there was no existing array, I have made one (`$years`) that does contain the model itself, not just the info, so it ends up looking like this: `$years[$current_year_id]->name`. I think this way is better, so I could change it so **external** also uses it, let me know.

Also, I have seen the Todo's for the **internal** method, I'll check it out in the future.

**Comment by laxsmi** [comment]
Perfect, everything seems to work now!

> For **internal**, since there was no existing array, I have made one (`$years`) that does contain the model itself, not just the info, so it ends up looking like this: `$years[$current_year_id]->name`. I think this way is better, so I could change it so **external** also uses it, let me know.

I agree, it's probably better to include the whole model. Do you want to update **external** before I merge your PR?

> Also, I have seen the Todo's for the **internal** method, I'll check it out in the future.

The main issue I see is that some _foreach_ loops have DB queries within the loop, which slows down execution and increases resource usage when the amount of data in the report is higher.

Your contribution is already making things a little better by eliminating one "looped query", but of course the nested loops are the worst and represent most of the total number of queries.

I will write some proper tests for these reports, which should allow to bring in more refactors in the future, without fear of breaking anything.

**Comment by marcmarina** [comment]
Okay, I have changed it for **external** too - better to be consistent on both pages. When the DB queries and the loops are revised, the arrays I've added will probably go away, but it's fixed for now.

**Comment by laxsmi** [comment]
@all-contributors please add marcmarina for code

**Comment by laxsmi** [comment]
Thank you @marcmarina for your contribution! I added you to the list of contributors in the README file. I'm glad the project raised your interest :)

**Comment by marcmarina** [comment]
Very nice! Thanks :D

**Pull request merged**
